on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  #pull_request:
  #  branches:
  #    - master
  # Also trigger on page_build, as well as release created events
  #page_build:
  #release:
  #  types: # This configuration does not affect the page_build event above
  #    - created

name: Build and Push Image to Amazon ECR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: front-end
        region: ap-northeast-1
        tags: latest,${{ github.sha }}
        create_repo: true
